services:
  dev:
    build: .
    image: aayusha123/readtheroad-dev
    container_name: readtheroad-dev
    volumes:
      - ./ingestion:/app/ingestion # ingestion code
      - ./ocr:/app/ocr # ocr code
      - ./models:/app/models
      - ./main.py:/app/main.py
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env # API keys, secrets

    restart: unless-stopped
